name: Test and release

on:
  push:
    branches: [ master ]
  pull_request:
    types: [synchronize, opened]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [api, ui]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install package
      working-directory: "./packages/${{ matrix.package }}"
      run: npm ci
    
    - name: Check for vulnerable dependencies in package
      working-directory: "./packages/${{ matrix.package }}"
      run: npm audit --audit-level high

    - name: Test
      working-directory: "./packages/${{ matrix.package }}"
      run: npm test

  deploy-test-stack:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    
    - name: Install root
      run: npm ci
    
    - name: Check for vulnerable dependencies in root
      run: npm audit --audit-level high
    
    - name: Install dependencies
      run: |
        npm ci
        npm --prefix ./packages/ui install
        npm --prefix ./packages/api install

    - name: Copy example.env.development to .env
      run: cp example.env.development .env

    - name: Setup AWS Credentials
      if: github.head_ref
      run: |
        mkdir ~/.aws
        echo "[myapp_dev]
        aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
      # TODO: How to also get the PR origin repo if it's coming from an external contributor
      # See: env.GITHUB_REF, env.GITHUB_HEAD_REF, GITHUB_BASE_REF https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables
        NODE_ENV=production && npm run deploy:dev -- --gitHubPullRequestBranch=${{ github.head_ref }}

    - name: Setup AWS Credentials
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        mkdir ~/.aws
        echo "[myapp_staging]
        aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" > ~/.aws/credentials
        npm run deploy:staging

    # TODO: Additional end-to-end tests

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [deploy-test-stack]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        npm ci
        npm --prefix ./packages/ui install
        npm --prefix ./packages/api install
      
    - name: Package
      run: npm run package
      
    - name: Release
      run: npx semantic-release
      env:
        # NOTE: GitHub Actions won't trigger on release when using the default GITHUB_TOKEN
        # Make sure the Personal Access Token is enabled for SSO if relevant to your organization/repo
        GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
